// Code generated by go generate forge validation v0.3; DO NOT EDIT.

package mailinglist

func (r reqCreatorLists) valid() error {
	if err := validhasCreatorID(r.CreatorID); err != nil {
		return err
	}
	if err := validAmount(r.Amount); err != nil {
		return err
	}
	return nil
}

func (r reqUserLists) valid() error {
	if err := validhasUserid(r.Userid); err != nil {
		return err
	}
	if err := validAmount(r.Amount); err != nil {
		return err
	}
	return nil
}

func (r reqListMsgs) valid() error {
	if err := validhasListid(r.Listid); err != nil {
		return err
	}
	if err := validAmount(r.Amount); err != nil {
		return err
	}
	return nil
}
