// Code generated by go generate. DO NOT EDIT.
package confmodel

import (
	"database/sql"
	"github.com/lib/pq"
)

const (
	modelTableName = "config"
)

const (
	modelSQLSetup = "CREATE TABLE config (config INT PRIMARY KEY, orgname VARCHAR(255) NOT NULL, creation_time BIGINT NOT NULL);"
)

func modelSetup(db *sql.DB) error {
	_, err := db.Exec(modelSQLSetup)
	return err
}

const (
	modelSQLGet = "SELECT config, orgname, creation_time FROM config WHERE config = $1;"
)

func modelGet(db *sql.DB, key int) (*Model, int, error) {
	m := &Model{}
	if err := db.QueryRow(modelSQLGet, key).Scan(&m.config, &m.Orgname, &m.CreationTime); err != nil {
		if err == sql.ErrNoRows {
			return nil, 2, err
		}
		return nil, 0, err
	}
	return m, 0, nil
}

const (
	modelSQLInsert = "INSERT INTO config (config, orgname, creation_time) VALUES ($1, $2, $3);"
)

func modelInsert(db *sql.DB, m *Model) (int, error) {
	_, err := db.Exec(modelSQLInsert, m.config, m.Orgname, m.CreationTime)
	if err != nil {
		if postgresErr, ok := err.(*pq.Error); ok {
			switch postgresErr.Code {
			case "23505": // unique_violation
				return 3, err
			default:
				return 0, err
			}
		}
	}
	return 0, nil
}

const (
	modelSQLUpdate = "UPDATE config SET (config, orgname, creation_time) = ($1, $2, $3) WHERE config = $1;"
)

func modelUpdate(db *sql.DB, m *Model) error {
	_, err := db.Exec(modelSQLUpdate, m.config, m.Orgname, m.CreationTime)
	return err
}

const (
	modelSQLDelete = "DELETE FROM config WHERE config = $1;"
)

func modelDelete(db *sql.DB, m *Model) error {
	_, err := db.Exec(modelSQLDelete, m.config)
	return err
}
