// Code generated by go generate forge model v0.3; DO NOT EDIT.

package model

import (
	"database/sql"
	"fmt"
	"strings"
)

func serverModelSetup(db *sql.DB, tableName string) error {
	_, err := db.Exec("CREATE TABLE IF NOT EXISTS " + tableName + " (serverid VARCHAR(31) PRIMARY KEY, name VARCHAR(255) NOT NULL, theme VARCHAR(4095) NOT NULL, creation_time BIGINT NOT NULL);")
	if err != nil {
		return err
	}
	return nil
}

func serverModelInsert(db *sql.DB, tableName string, m *Model) error {
	_, err := db.Exec("INSERT INTO "+tableName+" (serverid, name, theme, creation_time) VALUES ($1, $2, $3, $4);", m.ServerID, m.Name, m.Theme, m.CreationTime)
	if err != nil {
		return err
	}
	return nil
}

func serverModelInsertBulk(db *sql.DB, tableName string, models []*Model, allowConflict bool) error {
	conflictSQL := ""
	if allowConflict {
		conflictSQL = " ON CONFLICT DO NOTHING"
	}
	placeholders := make([]string, 0, len(models))
	args := make([]interface{}, 0, len(models)*4)
	for c, m := range models {
		n := c * 4
		placeholders = append(placeholders, fmt.Sprintf("($%d, $%d, $%d, $%d)", n+1, n+2, n+3, n+4))
		args = append(args, m.ServerID, m.Name, m.Theme, m.CreationTime)
	}
	_, err := db.Exec("INSERT INTO "+tableName+" (serverid, name, theme, creation_time) VALUES "+strings.Join(placeholders, ", ")+conflictSQL+";", args...)
	if err != nil {
		return err
	}
	return nil
}

func serverModelGetModelEqServerID(db *sql.DB, tableName string, serverid string) (*Model, error) {
	m := &Model{}
	if err := db.QueryRow("SELECT serverid, name, theme, creation_time FROM "+tableName+" WHERE serverid = $1;", serverid).Scan(&m.ServerID, &m.Name, &m.Theme, &m.CreationTime); err != nil {
		return nil, err
	}
	return m, nil
}

func serverModelGetModelHasServerIDOrdServerID(db *sql.DB, tableName string, serverid []string, orderasc bool, limit, offset int) ([]Model, error) {
	paramCount := 2
	args := make([]interface{}, 0, paramCount+len(serverid))
	args = append(args, limit, offset)
	var placeholdersserverid string
	{
		placeholders := make([]string, 0, len(serverid))
		for _, i := range serverid {
			paramCount++
			placeholders = append(placeholders, fmt.Sprintf("($%d)", paramCount))
			args = append(args, i)
		}
		placeholdersserverid = strings.Join(placeholders, ", ")
	}
	order := "DESC"
	if orderasc {
		order = "ASC"
	}
	res := make([]Model, 0, limit)
	rows, err := db.Query("SELECT serverid, name, theme, creation_time FROM "+tableName+" WHERE serverid IN (VALUES "+placeholdersserverid+") ORDER BY serverid "+order+" LIMIT $1 OFFSET $2;", args...)
	if err != nil {
		return nil, err
	}
	defer func() {
		if err := rows.Close(); err != nil {
		}
	}()
	for rows.Next() {
		m := Model{}
		if err := rows.Scan(&m.ServerID, &m.Name, &m.Theme, &m.CreationTime); err != nil {
			return nil, err
		}
		res = append(res, m)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return res, nil
}

func serverModelUpdModelEqServerID(db *sql.DB, tableName string, m *Model, serverid string) error {
	_, err := db.Exec("UPDATE "+tableName+" SET (serverid, name, theme, creation_time) = ROW($1, $2, $3, $4) WHERE serverid = $5;", m.ServerID, m.Name, m.Theme, m.CreationTime, serverid)
	if err != nil {
		return err
	}
	return nil
}

func serverModelDelEqServerID(db *sql.DB, tableName string, serverid string) error {
	_, err := db.Exec("DELETE FROM "+tableName+" WHERE serverid = $1;", serverid)
	return err
}
