// Code generated by go generate forge model v0.4.0; DO NOT EDIT.

package model

import (
	"context"
	"fmt"
	"strings"

	"xorkevin.dev/governor/service/db"
)

type (
	linkModelTable struct {
		TableName string
	}
)

func (t *linkModelTable) Setup(ctx context.Context, d db.SQLExecutor) error {
	_, err := d.ExecContext(ctx, "CREATE TABLE IF NOT EXISTS "+t.TableName+" (linkid VARCHAR(63) PRIMARY KEY, url VARCHAR(2047) NOT NULL, creatorid VARCHAR(31) NOT NULL, creation_time BIGINT NOT NULL);")
	if err != nil {
		return err
	}
	_, err = d.ExecContext(ctx, "CREATE INDEX IF NOT EXISTS "+t.TableName+"_creation_time_index ON "+t.TableName+" (creation_time);")
	if err != nil {
		return err
	}
	_, err = d.ExecContext(ctx, "CREATE INDEX IF NOT EXISTS "+t.TableName+"_creatorid__creation_time_index ON "+t.TableName+" (creatorid, creation_time);")
	if err != nil {
		return err
	}
	return nil
}

func (t *linkModelTable) Insert(ctx context.Context, d db.SQLExecutor, m *LinkModel) error {
	_, err := d.ExecContext(ctx, "INSERT INTO "+t.TableName+" (linkid, url, creatorid, creation_time) VALUES ($1, $2, $3, $4);", m.LinkID, m.URL, m.CreatorID, m.CreationTime)
	if err != nil {
		return err
	}
	return nil
}

func (t *linkModelTable) InsertBulk(ctx context.Context, d db.SQLExecutor, models []*LinkModel, allowConflict bool) error {
	conflictSQL := ""
	if allowConflict {
		conflictSQL = " ON CONFLICT DO NOTHING"
	}
	placeholders := make([]string, 0, len(models))
	args := make([]interface{}, 0, len(models)*4)
	for c, m := range models {
		n := c * 4
		placeholders = append(placeholders, fmt.Sprintf("($%d, $%d, $%d, $%d)", n+1, n+2, n+3, n+4))
		args = append(args, m.LinkID, m.URL, m.CreatorID, m.CreationTime)
	}
	_, err := d.ExecContext(ctx, "INSERT INTO "+t.TableName+" (linkid, url, creatorid, creation_time) VALUES "+strings.Join(placeholders, ", ")+conflictSQL+";", args...)
	if err != nil {
		return err
	}
	return nil
}

func (t *linkModelTable) GetLinkModelEqLinkID(ctx context.Context, d db.SQLExecutor, linkid string) (*LinkModel, error) {
	m := &LinkModel{}
	if err := d.QueryRowContext(ctx, "SELECT linkid, url, creatorid, creation_time FROM "+t.TableName+" WHERE linkid = $1;", linkid).Scan(&m.LinkID, &m.URL, &m.CreatorID, &m.CreationTime); err != nil {
		return nil, err
	}
	return m, nil
}

func (t *linkModelTable) DelEqLinkID(ctx context.Context, d db.SQLExecutor, linkid string) error {
	_, err := d.ExecContext(ctx, "DELETE FROM "+t.TableName+" WHERE linkid = $1;", linkid)
	return err
}

func (t *linkModelTable) DelHasLinkID(ctx context.Context, d db.SQLExecutor, linkids []string) error {
	paramCount := 0
	args := make([]interface{}, 0, paramCount+len(linkids))
	var placeholderslinkids string
	{
		placeholders := make([]string, 0, len(linkids))
		for _, i := range linkids {
			paramCount++
			placeholders = append(placeholders, fmt.Sprintf("($%d)", paramCount))
			args = append(args, i)
		}
		placeholderslinkids = strings.Join(placeholders, ", ")
	}
	_, err := d.ExecContext(ctx, "DELETE FROM "+t.TableName+" WHERE linkid IN (VALUES "+placeholderslinkids+");", args...)
	return err
}

func (t *linkModelTable) GetLinkModelEqCreatorIDOrdCreationTime(ctx context.Context, d db.SQLExecutor, creatorid string, orderasc bool, limit, offset int) ([]LinkModel, error) {
	order := "DESC"
	if orderasc {
		order = "ASC"
	}
	res := make([]LinkModel, 0, limit)
	rows, err := d.QueryContext(ctx, "SELECT linkid, url, creatorid, creation_time FROM "+t.TableName+" WHERE creatorid = $3 ORDER BY creation_time "+order+" LIMIT $1 OFFSET $2;", limit, offset, creatorid)
	if err != nil {
		return nil, err
	}
	defer func() {
		if err := rows.Close(); err != nil {
		}
	}()
	for rows.Next() {
		var m LinkModel
		if err := rows.Scan(&m.LinkID, &m.URL, &m.CreatorID, &m.CreationTime); err != nil {
			return nil, err
		}
		res = append(res, m)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return res, nil
}

type (
	brandModelTable struct {
		TableName string
	}
)

func (t *brandModelTable) Setup(ctx context.Context, d db.SQLExecutor) error {
	_, err := d.ExecContext(ctx, "CREATE TABLE IF NOT EXISTS "+t.TableName+" (creatorid VARCHAR(31), brandid VARCHAR(63), PRIMARY KEY (creatorid, brandid), creation_time BIGINT NOT NULL);")
	if err != nil {
		return err
	}
	_, err = d.ExecContext(ctx, "CREATE INDEX IF NOT EXISTS "+t.TableName+"_creation_time_index ON "+t.TableName+" (creation_time);")
	if err != nil {
		return err
	}
	_, err = d.ExecContext(ctx, "CREATE INDEX IF NOT EXISTS "+t.TableName+"_creatorid__creation_time_index ON "+t.TableName+" (creatorid, creation_time);")
	if err != nil {
		return err
	}
	return nil
}

func (t *brandModelTable) Insert(ctx context.Context, d db.SQLExecutor, m *BrandModel) error {
	_, err := d.ExecContext(ctx, "INSERT INTO "+t.TableName+" (creatorid, brandid, creation_time) VALUES ($1, $2, $3);", m.CreatorID, m.BrandID, m.CreationTime)
	if err != nil {
		return err
	}
	return nil
}

func (t *brandModelTable) InsertBulk(ctx context.Context, d db.SQLExecutor, models []*BrandModel, allowConflict bool) error {
	conflictSQL := ""
	if allowConflict {
		conflictSQL = " ON CONFLICT DO NOTHING"
	}
	placeholders := make([]string, 0, len(models))
	args := make([]interface{}, 0, len(models)*3)
	for c, m := range models {
		n := c * 3
		placeholders = append(placeholders, fmt.Sprintf("($%d, $%d, $%d)", n+1, n+2, n+3))
		args = append(args, m.CreatorID, m.BrandID, m.CreationTime)
	}
	_, err := d.ExecContext(ctx, "INSERT INTO "+t.TableName+" (creatorid, brandid, creation_time) VALUES "+strings.Join(placeholders, ", ")+conflictSQL+";", args...)
	if err != nil {
		return err
	}
	return nil
}

func (t *brandModelTable) GetBrandModelEqCreatorIDEqBrandID(ctx context.Context, d db.SQLExecutor, creatorid string, brandid string) (*BrandModel, error) {
	m := &BrandModel{}
	if err := d.QueryRowContext(ctx, "SELECT creatorid, brandid, creation_time FROM "+t.TableName+" WHERE creatorid = $1 AND brandid = $2;", creatorid, brandid).Scan(&m.CreatorID, &m.BrandID, &m.CreationTime); err != nil {
		return nil, err
	}
	return m, nil
}

func (t *brandModelTable) DelEqCreatorIDEqBrandID(ctx context.Context, d db.SQLExecutor, creatorid string, brandid string) error {
	_, err := d.ExecContext(ctx, "DELETE FROM "+t.TableName+" WHERE creatorid = $1 AND brandid = $2;", creatorid, brandid)
	return err
}

func (t *brandModelTable) DelEqCreatorIDHasBrandID(ctx context.Context, d db.SQLExecutor, creatorid string, brandids []string) error {
	paramCount := 1
	args := make([]interface{}, 0, paramCount+len(brandids))
	args = append(args, creatorid)
	var placeholdersbrandids string
	{
		placeholders := make([]string, 0, len(brandids))
		for _, i := range brandids {
			paramCount++
			placeholders = append(placeholders, fmt.Sprintf("($%d)", paramCount))
			args = append(args, i)
		}
		placeholdersbrandids = strings.Join(placeholders, ", ")
	}
	_, err := d.ExecContext(ctx, "DELETE FROM "+t.TableName+" WHERE creatorid = $1 AND brandid IN (VALUES "+placeholdersbrandids+");", args...)
	return err
}

func (t *brandModelTable) GetBrandModelEqCreatorIDOrdCreationTime(ctx context.Context, d db.SQLExecutor, creatorid string, orderasc bool, limit, offset int) ([]BrandModel, error) {
	order := "DESC"
	if orderasc {
		order = "ASC"
	}
	res := make([]BrandModel, 0, limit)
	rows, err := d.QueryContext(ctx, "SELECT creatorid, brandid, creation_time FROM "+t.TableName+" WHERE creatorid = $3 ORDER BY creation_time "+order+" LIMIT $1 OFFSET $2;", limit, offset, creatorid)
	if err != nil {
		return nil, err
	}
	defer func() {
		if err := rows.Close(); err != nil {
		}
	}()
	for rows.Next() {
		var m BrandModel
		if err := rows.Scan(&m.CreatorID, &m.BrandID, &m.CreationTime); err != nil {
			return nil, err
		}
		res = append(res, m)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return res, nil
}
