// Code generated by go generate forge model v0.3; DO NOT EDIT.

package model

import (
	"database/sql"
	"fmt"
	"strings"
)

func linkModelSetup(db *sql.DB, tableName string) error {
	_, err := db.Exec("CREATE TABLE IF NOT EXISTS " + tableName + " (linkid VARCHAR(63) PRIMARY KEY, url VARCHAR(2047) NOT NULL, creatorid VARCHAR(31) NOT NULL, creation_time BIGINT NOT NULL);")
	if err != nil {
		return err
	}
	_, err = db.Exec("CREATE INDEX IF NOT EXISTS " + tableName + "_creation_time_index ON " + tableName + " (creation_time);")
	if err != nil {
		return err
	}
	_, err = db.Exec("CREATE INDEX IF NOT EXISTS " + tableName + "_creatorid__creation_time_index ON " + tableName + " (creatorid, creation_time);")
	if err != nil {
		return err
	}
	return nil
}

func linkModelInsert(db *sql.DB, tableName string, m *LinkModel) error {
	_, err := db.Exec("INSERT INTO "+tableName+" (linkid, url, creatorid, creation_time) VALUES ($1, $2, $3, $4);", m.LinkID, m.URL, m.CreatorID, m.CreationTime)
	if err != nil {
		return err
	}
	return nil
}

func linkModelInsertBulk(db *sql.DB, tableName string, models []*LinkModel, allowConflict bool) error {
	conflictSQL := ""
	if allowConflict {
		conflictSQL = " ON CONFLICT DO NOTHING"
	}
	placeholders := make([]string, 0, len(models))
	args := make([]interface{}, 0, len(models)*4)
	for c, m := range models {
		n := c * 4
		placeholders = append(placeholders, fmt.Sprintf("($%d, $%d, $%d, $%d)", n+1, n+2, n+3, n+4))
		args = append(args, m.LinkID, m.URL, m.CreatorID, m.CreationTime)
	}
	_, err := db.Exec("INSERT INTO "+tableName+" (linkid, url, creatorid, creation_time) VALUES "+strings.Join(placeholders, ", ")+conflictSQL+";", args...)
	if err != nil {
		return err
	}
	return nil
}

func linkModelGetLinkModelEqLinkID(db *sql.DB, tableName string, linkid string) (*LinkModel, error) {
	m := &LinkModel{}
	if err := db.QueryRow("SELECT linkid, url, creatorid, creation_time FROM "+tableName+" WHERE linkid = $1;", linkid).Scan(&m.LinkID, &m.URL, &m.CreatorID, &m.CreationTime); err != nil {
		return nil, err
	}
	return m, nil
}

func linkModelDelEqLinkID(db *sql.DB, tableName string, linkid string) error {
	_, err := db.Exec("DELETE FROM "+tableName+" WHERE linkid = $1;", linkid)
	return err
}

func linkModelDelHasLinkID(db *sql.DB, tableName string, linkid []string) error {
	paramCount := 0
	args := make([]interface{}, 0, paramCount+len(linkid))
	var placeholderslinkid string
	{
		placeholders := make([]string, 0, len(linkid))
		for _, i := range linkid {
			paramCount++
			placeholders = append(placeholders, fmt.Sprintf("($%d)", paramCount))
			args = append(args, i)
		}
		placeholderslinkid = strings.Join(placeholders, ", ")
	}
	_, err := db.Exec("DELETE FROM "+tableName+" WHERE linkid IN (VALUES "+placeholderslinkid+");", args...)
	return err
}

func linkModelGetLinkModelOrdCreationTime(db *sql.DB, tableName string, orderasc bool, limit, offset int) ([]LinkModel, error) {
	order := "DESC"
	if orderasc {
		order = "ASC"
	}
	res := make([]LinkModel, 0, limit)
	rows, err := db.Query("SELECT linkid, url, creatorid, creation_time FROM "+tableName+" ORDER BY creation_time "+order+" LIMIT $1 OFFSET $2;", limit, offset)
	if err != nil {
		return nil, err
	}
	defer func() {
		if err := rows.Close(); err != nil {
		}
	}()
	for rows.Next() {
		m := LinkModel{}
		if err := rows.Scan(&m.LinkID, &m.URL, &m.CreatorID, &m.CreationTime); err != nil {
			return nil, err
		}
		res = append(res, m)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return res, nil
}

func linkModelGetLinkModelEqCreatorIDOrdCreationTime(db *sql.DB, tableName string, creatorid string, orderasc bool, limit, offset int) ([]LinkModel, error) {
	order := "DESC"
	if orderasc {
		order = "ASC"
	}
	res := make([]LinkModel, 0, limit)
	rows, err := db.Query("SELECT linkid, url, creatorid, creation_time FROM "+tableName+" WHERE creatorid = $3 ORDER BY creation_time "+order+" LIMIT $1 OFFSET $2;", limit, offset, creatorid)
	if err != nil {
		return nil, err
	}
	defer func() {
		if err := rows.Close(); err != nil {
		}
	}()
	for rows.Next() {
		m := LinkModel{}
		if err := rows.Scan(&m.LinkID, &m.URL, &m.CreatorID, &m.CreationTime); err != nil {
			return nil, err
		}
		res = append(res, m)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return res, nil
}
