// Code generated by go generate forge validation v0.3; DO NOT EDIT.

package oauth

func (r reqAppGet) valid() error {
	if err := validhasClientID(r.ClientID); err != nil {
		return err
	}
	return nil
}

func (r reqGetGroup) valid() error {
	if err := validAmount(r.Amount); err != nil {
		return err
	}
	if err := validOffset(r.Offset); err != nil {
		return err
	}
	return nil
}

func (r reqAppPost) valid() error {
	if err := validName(r.Name); err != nil {
		return err
	}
	if err := validURL(r.URL); err != nil {
		return err
	}
	if err := validRedirect(r.RedirectURI); err != nil {
		return err
	}
	if err := validhasCreatorID(r.CreatorID); err != nil {
		return err
	}
	return nil
}

func (r reqAppPut) valid() error {
	if err := validhasClientID(r.ClientID); err != nil {
		return err
	}
	if err := validName(r.Name); err != nil {
		return err
	}
	if err := validURL(r.URL); err != nil {
		return err
	}
	if err := validRedirect(r.RedirectURI); err != nil {
		return err
	}
	return nil
}
