mode: DEBUG
logoutput: STDOUT
port: 8080
baseurl: /api
maxreqsize: 2M
maxheadersize: 1M
maxconnread: 5s
maxconnheader: 2s
maxconnwrite: 5s
maxconnidle: 5s
alloworigins: []
allowpaths:
  - '^/api/oauth/(token|userinfo|jwks)$'
routerewrite:
  - host: go.governor.dev.localhost:8080
    methods: ['GET']
    pattern: '^/([A-Za-z0-9_-]{2,}(?:/image)?)$'
    replace: /api/courier/link/id/$1
  - host: governor.dev.localhost:8080
    methods: ['GET']
    pattern: '^\/\.well-known\/openid-configuration$'
    replace: /api/oauth/openid-configuration
vault:
  filesource: dc.anvil_out/governor/secrets.yaml
setupsecret: setupsecret
database:
  auth: dbauth
  dbname: postgres
  host: localhost
  port: 5432
  sslmode: disable
  hbinterval: 5
  hbmaxfail: 5
kvstore:
  auth: kvauth
  dbname: 0
  host: localhost
  port: 6379
  hbinterval: 5
  hbmaxfail: 5
objstore:
  auth: objauth
  host: localhost
  port: 9000
  sslmode: false
  location: us-east-1
  hbinterval: 5
  hbmaxfail: 5
events:
  auth: eventsauth
  host: localhost
  port: 4222
  hbinterval: 5
  hbmaxfail: 3
  minpullduration: 100ms
template:
  dir: anvil_out/governor/governor/templates
mail:
  auth: mailauth
  host: localhost
  port: 1025
  senderdomain: mail.xorkevin.com
  fromaddress: no-reply@xorkevin.com
  fromname: Governor
  streamsize: 200M
  msgsize: 2K
  mailkey: mailkey
role:
  rolecache: 24h
apikey:
  scopecache: 24h
token:
  tokensecret: tokensecret
  rsakey: rsakey
  issuer: http://governor.dev.localhost:8080
  audience: governor
gate:
  realm: governor
user:
  streamsize: 200M
  msgsize: 2K
  accesstime: 5m
  refreshtime: 4380h
  refreshcache: 24h
  confirmtime: 24h
  passwordresettime: 24h
  invitationtime: 24h
  usercachetime: 24h
  newloginemail: true
  passwordminsize: 8
  userapproval: false
  otpkey: otpkey
  otpissuer: Governor
  rolesummary:
    - user
    - admin
    - usr.gov.user
    - mod.gov.user
    - usr.gov.oauth
    - mod.gov.oauth
  email:
    url:
      base: http://localhost:3000
      emailchange: /a/confirm/email?key={{`{{.Userid}}`}}.{{`{{.Key}}`}}
      forgotpass: /x/resetpass?key={{`{{.Userid}}`}}.{{`{{.Key}}`}}
      newuser: /x/confirm?userid={{`{{.Userid}}`}}&key={{`{{.Key}}`}}
oauth:
  codetime: 1m
  accesstime: 5m
  refreshtime: 168h
  keycache: 24h
  realm: governor
  issuer: http://governor.dev.localhost:8080
  epauthorize: http://localhost:3000/oauth/auth
  ephost: http://governor.dev.localhost:8080
  epprofile: http://localhost:3000/u/{{`{{.Username}}`}}
  eppicture: http://localhost:3000/api/profile/id/{{`{{.Userid}}`}}/image
courier:
  fallbacklink: http://governor.dev.localhost:8080
  linkprefix: http://go.governor.dev.localhost:8080
  cachetime: 24h
