// Code generated by go generate. DO NOT EDIT.
package profilemodel

import (
	"database/sql"
	"github.com/lib/pq"
)

const (
	profileModelTableName = "profiles"
)

func profileModelSetup(db *sql.DB) error {
	_, err := db.Exec("CREATE TABLE profiles (userid BYTEA PRIMARY KEY, contact_email VARCHAR(255), bio VARCHAR(4095), profile_image_url VARCHAR(4095));")
	return err
}

func profileModelGet(db *sql.DB, key []byte) (*Model, int, error) {
	m := &Model{}
	if err := db.QueryRow("SELECT userid, contact_email, bio, profile_image_url FROM profiles WHERE userid = $1;", key).Scan(&m.Userid, &m.Email, &m.Bio, &m.Image); err != nil {
		if err == sql.ErrNoRows {
			return nil, 2, err
		}
		return nil, 0, err
	}
	return m, 0, nil
}

func profileModelInsert(db *sql.DB, m *Model) (int, error) {
	_, err := db.Exec("INSERT INTO profiles (userid, contact_email, bio, profile_image_url) VALUES ($1, $2, $3, $4);", m.Userid, m.Email, m.Bio, m.Image)
	if err != nil {
		if postgresErr, ok := err.(*pq.Error); ok {
			switch postgresErr.Code {
			case "23505": // unique_violation
				return 3, err
			default:
				return 0, err
			}
		}
	}
	return 0, nil
}

func profileModelUpdate(db *sql.DB, m *Model) error {
	_, err := db.Exec("UPDATE profiles SET (userid, contact_email, bio, profile_image_url) = ($1, $2, $3, $4) WHERE userid = $1;", m.Userid, m.Email, m.Bio, m.Image)
	return err
}

func profileModelDelete(db *sql.DB, m *Model) error {
	_, err := db.Exec("DELETE FROM profiles WHERE userid = $1;", m.Userid)
	return err
}
