// Code generated by go generate forge model v0.3; DO NOT EDIT.

package model

import (
	"database/sql"
	"fmt"
	"strings"
)

func memberModelSetup(db *sql.DB, tableName string) error {
	_, err := db.Exec("CREATE TABLE IF NOT EXISTS " + tableName + " (chatid VARCHAR(31), userid VARCHAR(31), PRIMARY KEY (chatid, userid), last_updated BIGINT NOT NULL);")
	if err != nil {
		return err
	}
	_, err = db.Exec("CREATE INDEX IF NOT EXISTS " + tableName + "_userid__chatid_index ON " + tableName + " (userid, chatid);")
	if err != nil {
		return err
	}
	_, err = db.Exec("CREATE INDEX IF NOT EXISTS " + tableName + "_userid__last_updated_index ON " + tableName + " (userid, last_updated);")
	if err != nil {
		return err
	}
	return nil
}

func memberModelInsert(db *sql.DB, tableName string, m *MemberModel) error {
	_, err := db.Exec("INSERT INTO "+tableName+" (chatid, userid, last_updated) VALUES ($1, $2, $3);", m.Chatid, m.Userid, m.LastUpdated)
	if err != nil {
		return err
	}
	return nil
}

func memberModelInsertBulk(db *sql.DB, tableName string, models []*MemberModel, allowConflict bool) error {
	conflictSQL := ""
	if allowConflict {
		conflictSQL = " ON CONFLICT DO NOTHING"
	}
	placeholders := make([]string, 0, len(models))
	args := make([]interface{}, 0, len(models)*3)
	for c, m := range models {
		n := c * 3
		placeholders = append(placeholders, fmt.Sprintf("($%d, $%d, $%d)", n+1, n+2, n+3))
		args = append(args, m.Chatid, m.Userid, m.LastUpdated)
	}
	_, err := db.Exec("INSERT INTO "+tableName+" (chatid, userid, last_updated) VALUES "+strings.Join(placeholders, ", ")+conflictSQL+";", args...)
	if err != nil {
		return err
	}
	return nil
}

func memberModelDelEqChatid(db *sql.DB, tableName string, chatid string) error {
	_, err := db.Exec("DELETE FROM "+tableName+" WHERE chatid = $1;", chatid)
	return err
}

func memberModelGetMemberModelEqUseridHasChatidOrdChatid(db *sql.DB, tableName string, userid string, chatid []string, orderasc bool, limit, offset int) ([]MemberModel, error) {
	paramCount := 3
	args := make([]interface{}, 0, paramCount+len(chatid))
	args = append(args, limit, offset, userid)
	var placeholderschatid string
	{
		placeholders := make([]string, 0, len(chatid))
		for _, i := range chatid {
			paramCount++
			placeholders = append(placeholders, fmt.Sprintf("($%d)", paramCount))
			args = append(args, i)
		}
		placeholderschatid = strings.Join(placeholders, ", ")
	}
	order := "DESC"
	if orderasc {
		order = "ASC"
	}
	res := make([]MemberModel, 0, limit)
	rows, err := db.Query("SELECT chatid, userid, last_updated FROM "+tableName+" WHERE userid = $3 AND chatid IN (VALUES "+placeholderschatid+") ORDER BY chatid "+order+" LIMIT $1 OFFSET $2;", args...)
	if err != nil {
		return nil, err
	}
	defer func() {
		if err := rows.Close(); err != nil {
		}
	}()
	for rows.Next() {
		m := MemberModel{}
		if err := rows.Scan(&m.Chatid, &m.Userid, &m.LastUpdated); err != nil {
			return nil, err
		}
		res = append(res, m)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return res, nil
}

func memberModelGetMemberModelHasChatidOrdChatid(db *sql.DB, tableName string, chatid []string, orderasc bool, limit, offset int) ([]MemberModel, error) {
	paramCount := 2
	args := make([]interface{}, 0, paramCount+len(chatid))
	args = append(args, limit, offset)
	var placeholderschatid string
	{
		placeholders := make([]string, 0, len(chatid))
		for _, i := range chatid {
			paramCount++
			placeholders = append(placeholders, fmt.Sprintf("($%d)", paramCount))
			args = append(args, i)
		}
		placeholderschatid = strings.Join(placeholders, ", ")
	}
	order := "DESC"
	if orderasc {
		order = "ASC"
	}
	res := make([]MemberModel, 0, limit)
	rows, err := db.Query("SELECT chatid, userid, last_updated FROM "+tableName+" WHERE chatid IN (VALUES "+placeholderschatid+") ORDER BY chatid "+order+" LIMIT $1 OFFSET $2;", args...)
	if err != nil {
		return nil, err
	}
	defer func() {
		if err := rows.Close(); err != nil {
		}
	}()
	for rows.Next() {
		m := MemberModel{}
		if err := rows.Scan(&m.Chatid, &m.Userid, &m.LastUpdated); err != nil {
			return nil, err
		}
		res = append(res, m)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return res, nil
}

func memberModelGetMemberModelEqChatidHasUseridOrdUserid(db *sql.DB, tableName string, chatid string, userid []string, orderasc bool, limit, offset int) ([]MemberModel, error) {
	paramCount := 3
	args := make([]interface{}, 0, paramCount+len(userid))
	args = append(args, limit, offset, chatid)
	var placeholdersuserid string
	{
		placeholders := make([]string, 0, len(userid))
		for _, i := range userid {
			paramCount++
			placeholders = append(placeholders, fmt.Sprintf("($%d)", paramCount))
			args = append(args, i)
		}
		placeholdersuserid = strings.Join(placeholders, ", ")
	}
	order := "DESC"
	if orderasc {
		order = "ASC"
	}
	res := make([]MemberModel, 0, limit)
	rows, err := db.Query("SELECT chatid, userid, last_updated FROM "+tableName+" WHERE chatid = $3 AND userid IN (VALUES "+placeholdersuserid+") ORDER BY userid "+order+" LIMIT $1 OFFSET $2;", args...)
	if err != nil {
		return nil, err
	}
	defer func() {
		if err := rows.Close(); err != nil {
		}
	}()
	for rows.Next() {
		m := MemberModel{}
		if err := rows.Scan(&m.Chatid, &m.Userid, &m.LastUpdated); err != nil {
			return nil, err
		}
		res = append(res, m)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return res, nil
}

func memberModelDelEqChatidHasUserid(db *sql.DB, tableName string, chatid string, userid []string) error {
	paramCount := 1
	args := make([]interface{}, 0, paramCount+len(userid))
	args = append(args, chatid)
	var placeholdersuserid string
	{
		placeholders := make([]string, 0, len(userid))
		for _, i := range userid {
			paramCount++
			placeholders = append(placeholders, fmt.Sprintf("($%d)", paramCount))
			args = append(args, i)
		}
		placeholdersuserid = strings.Join(placeholders, ", ")
	}
	_, err := db.Exec("DELETE FROM "+tableName+" WHERE chatid = $1 AND userid IN (VALUES "+placeholdersuserid+");", args...)
	return err
}

func memberModelGetMemberModelEqUseridOrdLastUpdated(db *sql.DB, tableName string, userid string, orderasc bool, limit, offset int) ([]MemberModel, error) {
	order := "DESC"
	if orderasc {
		order = "ASC"
	}
	res := make([]MemberModel, 0, limit)
	rows, err := db.Query("SELECT chatid, userid, last_updated FROM "+tableName+" WHERE userid = $3 ORDER BY last_updated "+order+" LIMIT $1 OFFSET $2;", limit, offset, userid)
	if err != nil {
		return nil, err
	}
	defer func() {
		if err := rows.Close(); err != nil {
		}
	}()
	for rows.Next() {
		m := MemberModel{}
		if err := rows.Scan(&m.Chatid, &m.Userid, &m.LastUpdated); err != nil {
			return nil, err
		}
		res = append(res, m)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return res, nil
}

func memberModelGetMemberModelEqUseridLtLastUpdatedOrdLastUpdated(db *sql.DB, tableName string, userid string, lastupdated int64, orderasc bool, limit, offset int) ([]MemberModel, error) {
	order := "DESC"
	if orderasc {
		order = "ASC"
	}
	res := make([]MemberModel, 0, limit)
	rows, err := db.Query("SELECT chatid, userid, last_updated FROM "+tableName+" WHERE userid = $3 AND last_updated < $4 ORDER BY last_updated "+order+" LIMIT $1 OFFSET $2;", limit, offset, userid, lastupdated)
	if err != nil {
		return nil, err
	}
	defer func() {
		if err := rows.Close(); err != nil {
		}
	}()
	for rows.Next() {
		m := MemberModel{}
		if err := rows.Scan(&m.Chatid, &m.Userid, &m.LastUpdated); err != nil {
			return nil, err
		}
		res = append(res, m)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return res, nil
}

func memberModelUpdmodelLastUpdatedEqChatid(db *sql.DB, tableName string, m *modelLastUpdated, chatid string) error {
	_, err := db.Exec("UPDATE "+tableName+" SET (last_updated) = ROW($1) WHERE chatid = $2;", m.LastUpdated, chatid)
	if err != nil {
		return err
	}
	return nil
}
