// Code generated by go generate forge validation v0.3; DO NOT EDIT.

package user

func (r reqAddAdmin) valid() error {
	if err := validUsername(r.Username); err != nil {
		return err
	}
	if err := validPassword(r.Password); err != nil {
		return err
	}
	if err := validEmail(r.Email); err != nil {
		return err
	}
	if err := validFirstName(r.Firstname); err != nil {
		return err
	}
	if err := validLastName(r.Lastname); err != nil {
		return err
	}
	return nil
}
