// Code generated by go generate. DO NOT EDIT.
package user

func (r reqUserRmSessions) valid() error {
	if err := validhasUserid(r.Userid); err != nil {
		return err
	}
	if err := validhasSessionIDs(r.SessionIDs); err != nil {
		return err
	}
	return nil
}
