// Code generated by go generate forge validation v0.2; DO NOT EDIT.

package user

func (r reqUserRmSessions) valid() error {
	if err := validhasUserid(r.Userid); err != nil {
		return err
	}
	if err := validSessionIDs(r.SessionIDs); err != nil {
		return err
	}
	return nil
}
