// Code generated by go generate forge validation v0.3; DO NOT EDIT.

package conduit

func (r reqGetLatestChats) valid() error {
	if err := validhasUserid(r.Userid); err != nil {
		return err
	}
	if err := validAmount(r.Amount); err != nil {
		return err
	}
	return nil
}

func (r reqGetChats) valid() error {
	if err := validhasUserid(r.Userid); err != nil {
		return err
	}
	if err := validhasChatids(r.Chatids); err != nil {
		return err
	}
	return nil
}

func (r reqCreateMsg) valid() error {
	if err := validhasUserid(r.Userid); err != nil {
		return err
	}
	if err := validhasChatid(r.Chatid); err != nil {
		return err
	}
	if err := validMsgkind(r.Kind); err != nil {
		return err
	}
	if err := validMsgvalue(r.Value); err != nil {
		return err
	}
	return nil
}

func (r reqGetMsgs) valid() error {
	if err := validhasUserid(r.Userid); err != nil {
		return err
	}
	if err := validhasChatid(r.Chatid); err != nil {
		return err
	}
	if err := validoptMsgkind(r.Kind); err != nil {
		return err
	}
	if err := validoptMsgid(r.Before); err != nil {
		return err
	}
	if err := validAmount(r.Amount); err != nil {
		return err
	}
	return nil
}

func (r reqDelMsg) valid() error {
	if err := validhasUserid(r.Userid); err != nil {
		return err
	}
	if err := validhasChatid(r.Chatid); err != nil {
		return err
	}
	if err := validhasMsgid(r.Msgid); err != nil {
		return err
	}
	return nil
}

func (r reqGetPresence) valid() error {
	if err := validhasUserid(r.Userid); err != nil {
		return err
	}
	if err := validhasUserids(r.Userids); err != nil {
		return err
	}
	return nil
}
