// Code generated by go generate forge validation v0.3; DO NOT EDIT.

package conduit

func (r reqCreateChat) valid() error {
	if err := validKind(r.Kind); err != nil {
		return err
	}
	if err := validName(r.Name); err != nil {
		return err
	}
	if err := validTheme(r.Theme); err != nil {
		return err
	}
	if err := validhasUserids(r.Userids); err != nil {
		return err
	}
	return nil
}
