// Code generated by go generate forge validation v0.3; DO NOT EDIT.

package conduit

func (r reqUpdateDM) valid() error {
	if err := validhasUserid(r.Userid); err != nil {
		return err
	}
	if err := validhasChatid(r.Chatid); err != nil {
		return err
	}
	if err := validName(r.Name); err != nil {
		return err
	}
	if err := validTheme(r.Theme); err != nil {
		return err
	}
	return nil
}
