// Code generated by go generate forge model v0.3; DO NOT EDIT.

package model

import (
	"database/sql"
	"fmt"
	"strings"
)

func friendModelSetup(db *sql.DB, tableName string) error {
	_, err := db.Exec("CREATE TABLE IF NOT EXISTS " + tableName + " (userid_1 VARCHAR(31), userid_2 VARCHAR(31), PRIMARY KEY (userid_1, userid_2), username VARCHAR(255) NOT NULL);")
	if err != nil {
		return err
	}
	_, err = db.Exec("CREATE INDEX IF NOT EXISTS " + tableName + "_userid_2_index ON " + tableName + " (userid_2);")
	if err != nil {
		return err
	}
	_, err = db.Exec("CREATE INDEX IF NOT EXISTS " + tableName + "_userid_1__username_index ON " + tableName + " (userid_1, username);")
	if err != nil {
		return err
	}
	return nil
}

func friendModelInsert(db *sql.DB, tableName string, m *FriendModel) error {
	_, err := db.Exec("INSERT INTO "+tableName+" (userid_1, userid_2, username) VALUES ($1, $2, $3);", m.Userid1, m.Userid2, m.Username)
	if err != nil {
		return err
	}
	return nil
}

func friendModelInsertBulk(db *sql.DB, tableName string, models []*FriendModel, allowConflict bool) error {
	conflictSQL := ""
	if allowConflict {
		conflictSQL = " ON CONFLICT DO NOTHING"
	}
	placeholders := make([]string, 0, len(models))
	args := make([]interface{}, 0, len(models)*3)
	for c, m := range models {
		n := c * 3
		placeholders = append(placeholders, fmt.Sprintf("($%d, $%d, $%d)", n+1, n+2, n+3))
		args = append(args, m.Userid1, m.Userid2, m.Username)
	}
	_, err := db.Exec("INSERT INTO "+tableName+" (userid_1, userid_2, username) VALUES "+strings.Join(placeholders, ", ")+conflictSQL+";", args...)
	if err != nil {
		return err
	}
	return nil
}

func friendModelDelEqUserid1(db *sql.DB, tableName string, userid1 string) error {
	_, err := db.Exec("DELETE FROM "+tableName+" WHERE userid_1 = $1;", userid1)
	return err
}

func friendModelDelEqUserid2(db *sql.DB, tableName string, userid2 string) error {
	_, err := db.Exec("DELETE FROM "+tableName+" WHERE userid_2 = $1;", userid2)
	return err
}

func friendModelGetFriendModelEqUserid1OrdUsername(db *sql.DB, tableName string, userid1 string, orderasc bool, limit, offset int) ([]FriendModel, error) {
	order := "DESC"
	if orderasc {
		order = "ASC"
	}
	res := make([]FriendModel, 0, limit)
	rows, err := db.Query("SELECT userid_1, userid_2, username FROM "+tableName+" WHERE userid_1 = $3 ORDER BY username "+order+" LIMIT $1 OFFSET $2;", limit, offset, userid1)
	if err != nil {
		return nil, err
	}
	defer func() {
		if err := rows.Close(); err != nil {
		}
	}()
	for rows.Next() {
		m := FriendModel{}
		if err := rows.Scan(&m.Userid1, &m.Userid2, &m.Username); err != nil {
			return nil, err
		}
		res = append(res, m)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return res, nil
}

func friendModelGetFriendModelEqUserid1LikeUsernameOrdUsername(db *sql.DB, tableName string, userid1 string, username string, orderasc bool, limit, offset int) ([]FriendModel, error) {
	order := "DESC"
	if orderasc {
		order = "ASC"
	}
	res := make([]FriendModel, 0, limit)
	rows, err := db.Query("SELECT userid_1, userid_2, username FROM "+tableName+" WHERE userid_1 = $3 AND username LIKE $4 ORDER BY username "+order+" LIMIT $1 OFFSET $2;", limit, offset, userid1, username)
	if err != nil {
		return nil, err
	}
	defer func() {
		if err := rows.Close(); err != nil {
		}
	}()
	for rows.Next() {
		m := FriendModel{}
		if err := rows.Scan(&m.Userid1, &m.Userid2, &m.Username); err != nil {
			return nil, err
		}
		res = append(res, m)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return res, nil
}

func friendModelUpdfriendUsernameEqUserid2(db *sql.DB, tableName string, m *friendUsername, userid2 string) error {
	_, err := db.Exec("UPDATE "+tableName+" SET (username) = ROW($1) WHERE userid_2 = $2;", m.Username, userid2)
	if err != nil {
		return err
	}
	return nil
}
