{{ $ns := .Vars.kube.namespace -}}
{{ $svc := .Vars.kube.service.name -}}
{{ $nssvc := printf "%s-%s" $ns $svc -}}
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ $ns }}
configMapGenerator:
  - name: {{ $svc }}-config
    files:
      - config.yaml
  - name: {{ $svc }}-templates
    files:
{{- range .Vars.templates }}
      - templates/{{ . }}
{{- end }}
resources:
  - service.yaml
  {{- with .Vars.kube.service.ingressRoute.entryPoints }}
  - ingressroute.yaml
  {{- end }}
