// Code generated by go generate forge model v0.3; DO NOT EDIT.

package model

import (
	"context"
	"fmt"
	"strings"

	"xorkevin.dev/governor/service/db"
)

type (
	serverModelTable struct {
		TableName string
	}
)

func (t *serverModelTable) Setup(ctx context.Context, d db.SQLExecutor) error {
	_, err := d.ExecContext(ctx, "CREATE TABLE IF NOT EXISTS "+t.TableName+" (serverid VARCHAR(31) PRIMARY KEY, name VARCHAR(255) NOT NULL, desc VARCHAR(255), theme VARCHAR(4095) NOT NULL, creation_time BIGINT NOT NULL);")
	if err != nil {
		return err
	}
	return nil
}

func (t *serverModelTable) Insert(ctx context.Context, d db.SQLExecutor, m *Model) error {
	_, err := d.ExecContext(ctx, "INSERT INTO "+t.TableName+" (serverid, name, desc, theme, creation_time) VALUES ($1, $2, $3, $4, $5);", m.ServerID, m.Name, m.Desc, m.Theme, m.CreationTime)
	if err != nil {
		return err
	}
	return nil
}

func (t *serverModelTable) InsertBulk(ctx context.Context, d db.SQLExecutor, models []*Model, allowConflict bool) error {
	conflictSQL := ""
	if allowConflict {
		conflictSQL = " ON CONFLICT DO NOTHING"
	}
	placeholders := make([]string, 0, len(models))
	args := make([]interface{}, 0, len(models)*5)
	for c, m := range models {
		n := c * 5
		placeholders = append(placeholders, fmt.Sprintf("($%d, $%d, $%d, $%d, $%d)", n+1, n+2, n+3, n+4, n+5))
		args = append(args, m.ServerID, m.Name, m.Desc, m.Theme, m.CreationTime)
	}
	_, err := d.ExecContext(ctx, "INSERT INTO "+t.TableName+" (serverid, name, desc, theme, creation_time) VALUES "+strings.Join(placeholders, ", ")+conflictSQL+";", args...)
	if err != nil {
		return err
	}
	return nil
}

func (t *serverModelTable) GetModelEqServerID(ctx context.Context, d db.SQLExecutor, serverid string) (*Model, error) {
	m := &Model{}
	if err := d.QueryRowContext(ctx, "SELECT serverid, name, desc, theme, creation_time FROM "+t.TableName+" WHERE serverid = $1;", serverid).Scan(&m.ServerID, &m.Name, &m.Desc, &m.Theme, &m.CreationTime); err != nil {
		return nil, err
	}
	return m, nil
}

func (t *serverModelTable) UpdModelEqServerID(ctx context.Context, d db.SQLExecutor, m *Model, serverid string) error {
	_, err := d.ExecContext(ctx, "UPDATE "+t.TableName+" SET (serverid, name, desc, theme, creation_time) = ROW($1, $2, $3, $4, $5) WHERE serverid = $6;", m.ServerID, m.Name, m.Desc, m.Theme, m.CreationTime, serverid)
	if err != nil {
		return err
	}
	return nil
}

func (t *serverModelTable) DelEqServerID(ctx context.Context, d db.SQLExecutor, serverid string) error {
	_, err := d.ExecContext(ctx, "DELETE FROM "+t.TableName+" WHERE serverid = $1;", serverid)
	return err
}
