services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: '--encoding UTF8 --auth-local=trust --auth-host=scram-sha-256'
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      LANG: C
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    entrypoint: ['redis-server']
    command: ['--requirepass', 'admin']
    ports:
      - 6379:6379

  minio:
    image: minio/minio:latest
    entrypoint: ['minio']
    command: ['server', '/var/lib/minio/data', '--console-address', ':9001']
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - miniodata:/var/lib/minio

  nats:
    image: nats:2-alpine
    entrypoint: ['nats-server']
    command: ['-c', '/etc/nats/server.conf']
    ports:
      - 4222:4222
    volumes:
      - natsdata:/var/lib/nats
      - ./natsetc:/etc/nats:ro

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  pgdata: {}
  miniodata: {}
  natsdata: {}
