apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: governor
configMapGenerator:
  - name: governor-config
    files:
      - config.yaml
  - name: governor-templates
    files:
      - templates/emailchange.html
      - templates/emailchangenotify.html
      - templates/emailchangenotify_subject.txt
      - templates/emailchangenotify.txt
      - templates/emailchange_subject.txt
      - templates/emailchange.txt
      - templates/forgotpass.html
      - templates/forgotpass_subject.txt
      - templates/forgotpass.txt
      - templates/newlogin.html
      - templates/newlogin_subject.txt
      - templates/newlogin.txt
      - templates/newuser.html
      - templates/newuser_subject.txt
      - templates/newuser.txt
      - templates/otpbackupused.html
      - templates/otpbackupused_subject.txt
      - templates/otpbackupused.txt
      - templates/otpratelimit.html
      - templates/otpratelimit_subject.txt
      - templates/otpratelimit.txt
      - templates/passchange.html
      - templates/passchange_subject.txt
      - templates/passchange.txt
      - templates/passreset.html
      - templates/passreset_subject.txt
      - templates/passreset.txt
resources:
  - service.yaml
  - ingressroute.yaml
