apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: governor
configMapGenerator:
  - name: governor-config
    files:
      - config.yaml
  - name: governor-templates
    files:
      - templates/emailchange.html.tmpl
      - templates/emailchangenotify.html.tmpl
      - templates/emailchangenotify_subject.txt.tmpl
      - templates/emailchangenotify.txt.tmpl
      - templates/emailchange_subject.txt.tmpl
      - templates/emailchange.txt.tmpl
      - templates/forgotpass.html.tmpl
      - templates/forgotpass_subject.txt.tmpl
      - templates/forgotpass.txt.tmpl
      - templates/newlogin.html.tmpl
      - templates/newlogin_subject.txt.tmpl
      - templates/newlogin.txt.tmpl
      - templates/newuser.html.tmpl
      - templates/newuser_subject.txt.tmpl
      - templates/newuser.txt.tmpl
      - templates/otpbackupused.html.tmpl
      - templates/otpbackupused_subject.txt.tmpl
      - templates/otpbackupused.txt.tmpl
      - templates/otpratelimit.html.tmpl
      - templates/otpratelimit_subject.txt.tmpl
      - templates/otpratelimit.txt.tmpl
      - templates/passchange.html.tmpl
      - templates/passchange_subject.txt.tmpl
      - templates/passchange.txt.tmpl
      - templates/passreset.html.tmpl
      - templates/passreset_subject.txt.tmpl
      - templates/passreset.txt.tmpl
resources:
  - service.yaml
  - ingressroute.yaml
