// Code generated by go generate forge validation v0.5.2; DO NOT EDIT.

package profile

func (r reqProfileModel) valid() error {
	if err := validhasUserid(r.Userid); err != nil {
		return err
	}
	if err := validEmail(r.Email); err != nil {
		return err
	}
	if err := validBio(r.Bio); err != nil {
		return err
	}
	return nil
}

func (r reqProfileGetID) valid() error {
	if err := validhasUserid(r.Userid); err != nil {
		return err
	}
	return nil
}

func (r reqGetProfiles) valid() error {
	if err := validhasUserids(r.Userids); err != nil {
		return err
	}
	return nil
}
