apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio

---
apiVersion: v1
kind: Service
metadata:
  name: minio-internal
spec:
  selector:
    app: minio
  ports:
    - name: minio
      port: 9000
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
    - name: minio
      port: 9000

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio-internal
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
        app.kubernetes.io/name: minio
        app.kubernetes.io/instance: minio
        app.kubernetes.io/version: latest
        app.kubernetes.io/component: objstore
        app.kubernetes.io/part-of: governor
        app.kubernetes.io/managed-by: anvil
    spec:
      serviceAccountName: minio
      initContainers:
        - name: getpass
          image: xorkevin/alpine-utils:3
          command: ['sh']
          args: ['/home/minio/init.sh']
          env:
            - name: CURL_BACKOFF
              valueFrom:
                configMapKeyRef:
                  name: minio-opts
                  key: curlbackoff
                  optional: true
            - name: CURL_REAUTH
              valueFrom:
                configMapKeyRef:
                  name: minio-opts
                  key: curlreauth
                  optional: true
            - name: VAULT_ADDR
              valueFrom:
                configMapKeyRef:
                  name: minio-opts
                  key: vaultaddr
            - name: VAULT_ROLE
              valueFrom:
                configMapKeyRef:
                  name: minio-opts
                  key: vaultrole
            - name: VAULT_KUBE_MOUNT
              valueFrom:
                configMapKeyRef:
                  name: minio-opts
                  key: vaultkubemount
            - name: KV_MOUNT
              valueFrom:
                configMapKeyRef:
                  name: minio-opts
                  key: kvmount
            - name: KV_PATH
              valueFrom:
                configMapKeyRef:
                  name: minio-opts
                  key: kvpath
          volumeMounts:
            - name: config-pass
              mountPath: /etc/miniopass
            - name: init-scripts
              mountPath: /home/minio
      containers:
        - name: minio
          image: minio/minio:latest
          command: ['minio']
          args: ['server', '/var/lib/minio/data', '--console-address', ':9001']
          env:
            - name: MINIO_ROOT_USER_FILE
              value: /etc/miniopass/username.txt
            - name: MINIO_ROOT_PASSWORD_FILE
              value: /etc/miniopass/pass.txt
          ports:
            - name: minio
              containerPort: 9000
            - name: minioconsole
              containerPort: 9001
          volumeMounts:
            - name: data
              mountPath: /var/lib/minio
            - name: config-pass
              mountPath: /etc/miniopass
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 15
      volumes:
        - name: config-pass
          emptyDir: {}
        - name: init-scripts
          configMap:
            name: minio-init-scripts
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
