apiVersion: v1
kind: ServiceAccount
metadata:
  name: register-governor

---
apiVersion: batch/v1
kind: Job
metadata:
  name: register-governor
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: register-governor
        app.kubernetes.io/name: register-governor
        app.kubernetes.io/instance: register-governor
        app.kubernetes.io/version: latest
        app.kubernetes.io/component: governor
        app.kubernetes.io/part-of: governor
        app.kubernetes.io/managed-by: anvil
    spec:
      serviceAccountName: register-governor
      restartPolicy: OnFailure
      containers:
        - name: register
          image: xorkevin/alpine-utils:3
          command: ['sh']
          args: ['/home/governor/register.sh']
          env:
            - name: PASS_LEN
              valueFrom:
                configMapKeyRef:
                  name: register-governor-opts
                  key: passlen
                  optional: true
            - name: RSA_BITS
              valueFrom:
                configMapKeyRef:
                  name: register-governor-opts
                  key: rsabits
                  optional: true
            - name: CURL_BACKOFF
              valueFrom:
                configMapKeyRef:
                  name: register-governor-opts
                  key: curlbackoff
                  optional: true
            - name: CURL_REAUTH
              valueFrom:
                configMapKeyRef:
                  name: register-governor-opts
                  key: curlreauth
                  optional: true
            - name: VAULT_ADDR
              valueFrom:
                configMapKeyRef:
                  name: register-governor-opts
                  key: vaultaddr
            - name: VAULT_ROLE
              valueFrom:
                configMapKeyRef:
                  name: register-governor-opts
                  key: vaultrole
            - name: VAULT_KUBE_MOUNT
              valueFrom:
                configMapKeyRef:
                  name: register-governor-opts
                  key: vaultkubemount
            - name: KV_MOUNT
              valueFrom:
                configMapKeyRef:
                  name: register-governor-opts
                  key: kvmount
            - name: KV_PATH_SETUP
              valueFrom:
                configMapKeyRef:
                  name: register-governor-opts
                  key: kvpathsetup
            - name: KV_PATH_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: register-governor-opts
                  key: kvpathtoken
            - name: KV_PATH_RSA
              valueFrom:
                configMapKeyRef:
                  name: register-governor-opts
                  key: kvpathrsa
            - name: KV_PATH_OTP
              valueFrom:
                configMapKeyRef:
                  name: register-governor-opts
                  key: kvpathotp
            - name: KV_PATH_MAIL
              valueFrom:
                configMapKeyRef:
                  name: register-governor-opts
                  key: kvpathmail
          volumeMounts:
            - name: register-scripts
              mountPath: /home/governor
      volumes:
        - name: register-scripts
          configMap:
            name: governor-register-scripts
